### ISSUE TITLE
Error on Re fetch dispatcher flush

### ISSUE THREAD

**Issue by rgravitvl** [cqsupport/webinar-dispatchercache#1]
After install the re-fetch cache package, changes setting of publsih agent as per webinar.But not able to do Test Connection as I get following error.

28.05.2015 11:26:51.798 _INFO_ [oak-executor-185] com.day.cq.replication.impl.ConfigManagerImpl Configuration for agent at /etc/replication/agents.publish/flush is active.
28.05.2015 11:26:51.798 _INFO_ [oak-executor-185] com.day.cq.replication.impl.AgentManagerImpl AgentConfig at /etc/replication/agents.publish/flush updated.
28.05.2015 11:26:51.798 _INFO_ [oak-executor-185] com.day.cq.replication.Agent.flush Agent stopped.
28.05.2015 11:26:51.798 _INFO_ [oak-executor-185] com.day.cq.replication.Agent.flush Agent stopped for (re)configuration
28.05.2015 11:26:51.798 _INFO_ [oak-executor-185] com.day.cq.replication.Agent.flush Agent configuration updated at /etc/replication/agents.publish/flush/jcr:content
28.05.2015 11:26:51.798 _INFO_ [oak-executor-185] com.day.cq.replication.Agent.flush Agent updated. State is enabled and valid
28.05.2015 11:26:51.798 _INFO_ [oak-executor-185] com.day.cq.replication.Agent.flush Agent started.
28.05.2015 11:26:53.802 _INFO_ [ReplicateOnModification Processor] com.day.cq.replication.impl.ReplicatorImpl Setting up replication with options: ReplicationOptions{synchronous=false, revision='null', suppressStatusUpdate=true, suppressVersions=true, filter=com.day.cq.wcm.core.impl.event.ReplicateOnModification$1@7b796d30, aggregateHandler=null}
28.05.2015 11:26:53.803 _INFO_ [ReplicateOnModification Processor] com.day.cq.replication.Agent.flush Creating content for path /etc/replication/agents.publish/flush
28.05.2015 11:26:53.803 _ERROR_ [ReplicateOnModification Processor] com.day.cq.replication.Agent.flush Error while building replication content java.lang.NullPointerException
28.05.2015 11:26:53.804 _ERROR_ [ReplicateOnModification Processor] com.day.cq.replication.impl.ReplicatorImpl Error while building replication content.
java.lang.NullPointerException: null
    at com.day.cq.replication.impl.AgentImpl.buildContent(AgentImpl.java:349)
    at com.day.cq.replication.impl.AgentImpl.buildContent(AgentImpl.java:324)
    at com.day.cq.replication.impl.ReplicatorImpl.buildContents(ReplicatorImpl.java:498)
    at com.day.cq.replication.impl.ReplicatorImpl.replicate(ReplicatorImpl.java:376)
    at com.day.cq.wcm.core.impl.event.ReplicateOnModification.replicate(ReplicateOnModification.java:271)
    at com.day.cq.wcm.core.impl.event.ReplicateOnModification.run(ReplicateOnModification.java:216)
    at java.lang.Thread.run(Thread.java:745)
28.05.2015 11:26:53.804 _INFO_ [ReplicateOnModification Processor] com.day.cq.replication.impl.ReplicatorImpl Processed replication: setup 0ms, checked 1ms, pre 0ms, build 1ms, queued 0ms, status 0ms, total 2ms
28.05.2015 11:26:53.804 _INFO_ [ReplicateOnModification Processor] com.day.cq.wcm.core.impl.event.ReplicateOnModification Auto-Replicated ACTIVATE of /etc/replication/agents.publish/flush
28.05.2015 11:27:00.001 _INFO_ [pool-9-thread-5] com.apple.haiku.cm.scheduler.AuditLogScheduler *****_In Audit Log Scheduler**_**
28.05.2015 11:27:00.002 _INFO_ [pool-9-thread-1] com.apple.haiku.cm.scheduler.MigrationContentScheduler **\* In Migration Content Scheduler run method ***
28.05.2015 11:27:00.002 _INFO_ [pool-9-thread-1] com.apple.haiku.cm.scheduler.MigrationContentScheduler **\* I/O ERROR. Configured Directory is not accessible. ***
28.05.2015 11:27:00.002 _INFO_ [pool-9-thread-1] com.apple.ist.itranslate.services.cq.impl.LocalizationAuditNodePurger **\* In Haiku Localized Audit Node Purge Scheduler run method ***
28.05.2015 11:27:00.003 _INFO_ [pool-9-thread-3] com.apple.ist.itranslate.services.cq.impl.LocalizedContentScheduler **\* In Haiku Localized Content Import Scheduler run method ***
28.05.2015 11:27:00.003 _INFO_ [pool-9-thread-3] com.apple.ist.itranslate.services.cq.impl.LocalizedContentScheduler **\* In Import Scheduler ***
28.05.2015 11:27:00.003 _INFO_ [pool-9-thread-3] com.apple.ist.itranslate.services.cq.impl.LocalizedContentScheduler **\* Add item threshold 10
28.05.2015 11:27:00.005 _INFO_ [pool-9-thread-3] com.apple.ist.itranslate.services.cq.impl.LocalizedContentScheduler **\* List size 0
28.05.2015 11:27:00.006 _INFO_ [pool-9-thread-1] com.apple.ist.itranslate.services.cq.impl.LocalizationAuditNodePurger **\* Directory path doesn't exist ***
28.05.2015 11:27:00.007 _INFO_ [pool-9-thread-1] com.apple.ist.itranslate.services.cq.impl.LocalizationAuditNodePurger **\* Re writing nodes ***

Please help me out to resolve this issue. Thanks in advance.

**Comment by andrewmkhoury** [comment]
Hi can you send me a screenshot of your dispatcher flush agent config?
It seems it's failing with the contentbuilder, make sure the bundle got
installed and that you have set the correct "Serialization Type" in the
agent.

**Comment by lgc0313** [comment]
I have the same problem.

**Comment by andrewmkhoury** [comment]
@lgc0313 what version of AEM are you using?
